services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DB_web_root
      MYSQL_DATABASE: DB_web
      MYSQL_USER: DB_web_user
      MYSQL_PASSWORD: DB_web_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: